package service

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/nkowanitemwani/amp-digital-library-backend/internal/models"
	"github.com/nkowanitemwani/amp-digital-library-backend/internal/repository"
	"github.com/nkowanitemwani/amp-digital-library-backend/storage"
)

// =============================================================
// QUIZ SERVICE
// Handles fetching questions for a book and recording quiz attempts.
// Questions are generated by the processor — this service only reads
// them and records student responses.
// =============================================================

var (
	// ErrQuestionsNotReady is returned when a book exists but its
	// questions have not been generated yet.
	ErrQuestionsNotReady = errors.New("quiz questions are not ready yet — please try again shortly")

	// ErrWrongAnswerCount is returned when the number of submitted
	// answers does not match the number of questions.
	ErrWrongAnswerCount = errors.New("number of answers does not match number of questions")
)

// QuizService handles quiz question retrieval and attempt recording.
type QuizService struct {
	questionRepo *repository.QuestionRepository
	attemptRepo  *repository.AttemptRepository
	bookRepo     *repository.BookRepository
	gradeRepo    *repository.GradeRepository
	auditRepo    *repository.AuditRepository
	store        storage.Storage
}

// NewQuizService creates a QuizService with its dependencies.
func NewQuizService(
	questionRepo *repository.QuestionRepository,
	attemptRepo *repository.AttemptRepository,
	bookRepo *repository.BookRepository,
	gradeRepo *repository.GradeRepository,
	auditRepo *repository.AuditRepository,
	store storage.Storage,
) *QuizService {
	return &QuizService{
		questionRepo: questionRepo,
		attemptRepo:  attemptRepo,
		bookRepo:     bookRepo,
		gradeRepo:    gradeRepo,
		auditRepo:    auditRepo,
		store:        store,
	}
}

func (s *QuizService) getBook(ctx context.Context, gradeID, bookID string) (*models.Book, error) {
	if gradeID == "" {
		return s.bookRepo.GetByIDAdmin(ctx, bookID)
	}
	return s.bookRepo.GetByID(ctx, bookID, gradeID)
}

// GetQuestions returns all questions for a book's quiz.
// The correct answer index is stripped from the response — students
// must not receive answers before submitting. Correct indices are
// only included in the AttemptResponse after submission.
//
// gradeID from the JWT is used to verify the book belongs to this
// grade before returning questions.
func (s *QuizService) GetQuestions(ctx context.Context, gradeID, bookID string) ([]*models.QuestionResponse, error) {
	// Verify the book belongs to this grade.
	book, err := s.getBook(ctx, bookID, gradeID)
	if errors.Is(err, repository.ErrNotFound) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get book: %w", err)
	}

	// Check the book's audio is ready before serving questions —
	// students should listen first, then take the quiz.
	if book.Status != models.BookStatusReady {
		return nil, ErrQuestionsNotReady
	}

	questions, err := s.questionRepo.GetByBook(ctx, bookID)
	if err != nil {
		return nil, fmt.Errorf("get questions: %w", err)
	}

	if len(questions) == 0 {
		return nil, ErrQuestionsNotReady
	}

	// Build response — strip correct_index, resolve audio URLs.
	responses := make([]*models.QuestionResponse, len(questions))
	for i, q := range questions {
		resp := &models.QuestionResponse{
			ID:           q.ID,
			QuestionText: q.QuestionText,
			Options:      q.Options,
			OrderIndex:   q.OrderIndex,
		}

		// Resolve presigned audio URL if question audio is ready.
		if q.AudioStatus == models.BookStatusReady && q.QuestionAudioPath != nil {
			url, err := s.store.SignedURL(ctx, *q.QuestionAudioPath, storage.AudioSignedURLTTL)
			if err == nil {
				resp.QuestionAudioURL = url
			}
		}

		responses[i] = resp
	}

	return responses, nil
}

// SubmitAttempt records a completed quiz and returns the results.
// Answers are validated against the stored correct indices and a
// score is calculated. The full result including correct answers
// is returned so the teacher can review with the student.
func (s *QuizService) SubmitAttempt(ctx context.Context, gradeID, bookID string, req *models.SubmitAttemptRequest, preview bool) (*models.AttemptResponse, error) {
	// Verify ownership.
	_, err := s.getBook(ctx, bookID, gradeID)
	if errors.Is(err, repository.ErrNotFound) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get book: %w", err)
	}

	// Fetch questions to validate and score the answers.
	questions, err := s.questionRepo.GetByBook(ctx, bookID)
	if err != nil {
		return nil, fmt.Errorf("get questions for scoring: %w", err)
	}

	if len(req.Answers) != len(questions) {
		return nil, ErrWrongAnswerCount
	}

	// Score the attempt — compare each submitted answer to the
	// stored correct_index for that question.
	score := 0
	correctIndices := make([]int, len(questions))

	for i, q := range questions {
		correctIndices[i] = q.CorrectIndex
		if i < len(req.Answers) && req.Answers[i] == q.CorrectIndex {
			score++
		}
	}

	// Persist the attempt.
	if !preview {
		_, err := s.attemptRepo.Create(ctx, &models.QuizAttempt{
			BookID:  bookID,
			GradeID: gradeID,
			Score:   score,
			Total:   len(questions),
			Answers: req.Answers,
		})
		if err != nil {
			return nil, fmt.Errorf("save attempt: %w", err)
		}

		s.auditRepo.Log(ctx, &models.AuditEntry{
			SchoolID: nil, // grade-level event, school_id not in context here
			Action:   "quiz.completed",
			Entity:   "book",
			EntityID: &bookID,
			Metadata: map[string]string{
				"grade_id": gradeID,
				"score":    fmt.Sprintf("%d/%d", score, len(questions)),
			},
		})
	}

	return &models.AttemptResponse{
		Score:   score,
		Total:   len(questions),
		Answers: req.Answers,
		Correct: correctIndices,
		Passed:  float64(score)/float64(len(questions)) >= 0.75,
	}, nil
}

// GetGradeProgress returns a progress summary for all books in a grade.
// Used by the teacher dashboard to see how the grade is performing
// across all quiz-enabled books.
func (s *QuizService) GetGradeProgress(ctx context.Context, schoolID, gradeID string) (*models.GradeProgressResponse, error) {
	// Verify grade belongs to school.
	grade, err := s.gradeRepo.GetByID(ctx, gradeID, schoolID)
	if errors.Is(err, repository.ErrNotFound) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get grade: %w", err)
	}

	// Fetch all attempts for this grade.
	attempts, err := s.attemptRepo.GetByGrade(ctx, gradeID)
	if err != nil {
		return nil, fmt.Errorf("get attempts: %w", err)
	}

	// Group attempts by book_id.
	type bookStats struct {
		title      string
		unitNumber int
		attempts   int
		bestScore  int
		totalScore int
		total      int
	}
	byBook := map[string]*bookStats{}

	for _, a := range attempts {
		if _, ok := byBook[a.BookID]; !ok {
			// Fetch book title on first encounter.
			// This is intentionally lazy — only fetches books that have
			// been attempted, not every book in the grade.
			book, err := s.getBook(ctx, a.BookID, gradeID)
			if err != nil {
				continue // book may have been deleted — skip gracefully
			}
			byBook[a.BookID] = &bookStats{
				title:      book.Title,
				unitNumber: book.UnitNumber,
				total:      a.Total,
			}
		}

		stats := byBook[a.BookID]
		stats.attempts++
		stats.totalScore += a.Score
		if a.Score > stats.bestScore {
			stats.bestScore = a.Score
		}
	}

	// Build response.
	books := make([]models.BookProgress, 0, len(byBook))
	for bookID, stats := range byBook {
		avg := 0.0
		if stats.attempts > 0 {
			avg = float64(stats.totalScore) / float64(stats.attempts)
		}
		books = append(books, models.BookProgress{
			BookID:     bookID,
			Title:      stats.title,
			UnitNumber: stats.unitNumber,
			Attempts:   stats.attempts,
			BestScore:  stats.bestScore,
			TotalQ:     stats.total,
			AvgScore:   avg,
		})
	}

	return &models.GradeProgressResponse{
		GradeID:   gradeID,
		GradeName: grade.Name,
		Books:     books,
	}, nil
}

// GetDialogueURL returns a presigned URL for a book's teaching dialogue audio.
// Returns ErrQuestionsNotReady if dialogue generation is not complete.
func (s *QuizService) GetDialogueURL(ctx context.Context, gradeID, bookID string) (string, error) {
	book, err := s.getBook(ctx, bookID, gradeID)
	if errors.Is(err, repository.ErrNotFound) {
		return "", ErrNotFound
	}
	if err != nil {
		return "", fmt.Errorf("get book: %w", err)
	}

	if book.DialogueStatus != models.BookStatusReady || book.DialogueAudioPath == nil {
		return "", ErrQuestionsNotReady
	}

	url, err := s.store.SignedURL(ctx, *book.DialogueAudioPath, storage.AudioSignedURLTTL)
	if err != nil {
		return "", fmt.Errorf("sign dialogue url: %w", err)
	}

	return url, nil
}

// dialogueTTL is intentionally the same as audio — 1 hour per session.
var _ = time.Hour // keep time import used
